apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service-a.fullname" . }}
  labels:
    {{- include "service-a.labels" . | nindent 4 }}
data:
  {{- if .Values.env }}
  {{- range $key,$val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}