apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "service-a.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "service-a.selectorLabels" . | nindent 6 }}
