name: test

on:
  push:
    branches:
      - "feature/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - run: |
        echo "----> ${{ github.ref_name }}"
        REF="${{ github.ref_name }}" echo "small=${REF,,}" >> $GITHUB_ENV

    - run: echo "XXXXXX ${{ env.small }}"
    - run: cat $GITHUB_ENV
