name: test

on:
  push:
    branches:
      - "feature/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "small=${{ github.ref_name }}" >> $GITHUB_ENV

      - run: echo "XXXXXX ${{ env.small }}"
      - run: cat $GITHUB_ENV
