name: test

on:
  push:
    branches:
      - "feature/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - run:
        export REF=${{ github.ref_name }}
        echo "small=${REF,,}" >> $GITHUB_ENV

    - run: echo "XXXXXX ${{ env.small }}"
