name: test

on:
  push:
    branches:
      - "feature/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - run: |
        export RRR=${{ github.ref_name }}
        echo "--->${{ env.RRR }}"
        echo "small=${RRR,,}" >> $GITHUB_ENV

    - run: echo "XXXXXX ${{ env.small }}"
    - run: cat $GITHUB_ENV
